# Generated by Django 5.0 on 2024-01-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api8', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
